### ISSUE TITLE
OpenCV 3.2

### ISSUE THREAD

**Issue by ruslo** [hunter-packages/opencv#13]
From https://github.com/ruslo/hunter/issues/683#issue-210111361:
```
there is at least two bugfix we need in OpenCV 3.2 compare to 3.1
```

@Ubiquite +cc

**Comment by Ubiquite** [comment]
I tested opencv 3.2 hunterized like the 3.1 and so far it works.

I created a branch hunter-3.2 on commit tagged 3.2 and rebased commits from hunter-3.1 on top of it :
https://github.com/Ubiquite/opencv/tree/hunter-3.2.0

**Comment by ruslo** [comment]
Branch [hunter-3.2.0](https://github.com/hunter-packages/opencv/tree/hunter-3.2.0) created, please send pull request there. Thanks.

**Comment by xsacha** [comment]
> and rebased commits from hunter-3.1 on top of it :

Most of the changes seem to be in the 3.0 branch for some reason, rather than 3.1.

Edit: By the way, already merged? So this can be closed.

**Comment by ruslo** [comment]
> Most of the changes seem to be in the 3.0 branch for some reason, rather than 3.1

Hunter use 3.1 version now, so it should be enough to have patches hunter-3.1.0 only

> By the way, already merged? So this can be closed

Yes
