### ISSUE TITLE
cmake/OpenCVCompilerOptions: incorrect else() else()

### ISSUE THREAD

**Issue by headupinclouds** [hunter-packages/opencv#16]
https://github.com/hunter-packages/opencv/blob/hunter-3.2.0/cmake/OpenCVCompilerOptions.cmake#L4-L23

**Comment by xsacha** [comment]
This is how it came in 3.2.0 release?
Does CMake fail here or ignores it?

**Comment by headupinclouds** [comment]
I noticed the same thing.  This only failed in a Linux + GCC toolchain, but seemed to work fine on OS X w/ various other toolchains: android, iOS, Xcode.   This was using ruslo's bundled polly ci dependencies, so the cmake version would have been the same.  I will try to get a pointer to a CI log for this and we can send a PR upstream.

**Comment by xsacha** [comment]
This was fixed and can be closed.
