### ISSUE TITLE
Allow building with system Qt instead of Hunter Qt

### ISSUE THREAD

**Issue by xsacha** [hunter-packages/opencv#20]
Since the Hunter Qt is stuck at 5.5, I would like the ability to use my system Qt instead.

If I try to use Qt4 to provide GUI in OpenCV, this conflicts with the Qt5.
I haven't had much luck with GTK and it seems like extreme lengths to get GUI working.

So, I propose a define to allow us to use system Qt package.

**Comment by ruslo** [comment]
I doubt this will happen:
* https://docs.hunter.sh/en/latest/faq/interaction-with-other-package-managers.html

There is proposal:
* https://github.com/ruslo/hunter/issues/501

But here is the comment why this will not work for Qt:
* https://github.com/forexample/android-cmake/issues/1#issuecomment-254098171

**Comment by xsacha** [comment]
Hmm the problem is I currently can't see any way to get my imshow working in Qt with Hunter.
I may have to use that external third party imshow package.

**Comment by ruslo** [comment]
`imshow` is in Hunter:
* https://docs.hunter.sh/en/latest/packages/pkg/imshow.html

You need to "teach" Qt build scheme to find and integrate it into build. E.g. similar to GStreamer:
* https://github.com/ruslo/hunter/blob/bcf7e82229b167464b2b2cebea61486294bb6ef7/cmake/projects/Qt/schemes/url_sha1_qt.cmake.in#L202-L208

**Comment by xsacha** [comment]
That imshow package unfortunately doesn't work in the same way and requires a whole host of opengl development headers.

The OpenCV package has already been taught to integrate Qt5 from hunter in to the build -- this is the problem.
Qt is a massive package to compile from source and happens to already be installed on a large number of Linux distros. By using hunter and fixing the Qt integration for OpenCV, I sign myself up to large recompiles (whenever deps change), an outdated version of Qt and extra memory usage in way of loading additional DLLs.
